---

# yamllint disable rule:line-length rule:comments-indentation

trigger:
  schedule:
    hourly:
      minute: 32

input:
  search:
    timeout: '5m'
    request:

      indices:
        - '*-*'
        - '-.*'

      body:

        size: 0
        query:
          bool:
            must:
              - exists:
                  field: '@timestamp'

condition:
  script:
    inline: |
      HashMap test = ['test': 23];
      if (params.getOrDefault('return_boolean', false)) {
        return false;
      } else {
        return test;
      }
    params:
      return_boolean: True

transform:
  script:
    inline: |
      HashMap test = ['test': 23];
      if (params.getOrDefault('return_boolean', false)) {
        return false;
      } else {
        return test;
      }

actions:
  log:
    logging:
      level: info
      text: 'Watch payload to be indexed by Elasticsearch: {{ctx.payload}}'
